### ISSUE TITLE
Runs at 5 fps on my wooden pc

### ISSUE THREAD

**Issue by Majiick** [yungrazr/OOP_Assignment1#1]
plz optimize

**Comment by Majiick** [comment]
since your last update it has increased to 10 fps, still on my wooden pc although i'd like if we can reach the 20 fps mark like old school rs, pls optimize more......

**Comment by yungrazr** [comment]
Hmmmm.. runs fine on my giga PC that has 4x Titan X (2016) and Intel Core i7 6660k !
